export const constelation = { 
  // Sun in all zodiac signs
  suninaries: ['energický lídr', 'odvážný a akční'],
  sunintaurus: ['stálý a pracovitý', 'materiálně založený'],
  suningemini: ['komunikativní a zvídavý', 'všestranný'],
  sunincancer: ['citlivý a starostlivý', 'rodinně zaměřený'],
  suninleo: ['sebevědomý lídr', 'hrdý a vznešený'],
  suninvirgo: ['metodický a organizovaný', 'pozorný k detailům'],
  suninlibra: ['harmonický a spravedlivý', 'společenský'],
  suninscorpio: ['intenzivní a vášnivý', 'tajemný'],
  suninsagittarius: ['dobrodružný a idealistický', 'hledající pravdu'],
  sunincapricorn: ['ambiciózní a disciplinovaný', 'pracovitý a zodpovědný'],
  suninaquarius: ['nezávislý a originální', 'vizionářský'],
  suninpisces: ['snílek a empatický', 'duchovně zaměřený'],

  // Moon in all zodiac signs
  mooninaries: ['impulzivní a citově přímý', 'rychlá emotivní reakce'],
  moonintaurus: ['klidný a stabilní', 'emocionálně ukotvený'],
  mooningemini: ['proměnlivý a zvědavý', 'potřeba komunikace'],
  moonincancer: ['emocionálně hluboký', 'rodinně zaměřený'],
  mooninleo: ['sebevědomý a dramatický', 'potřeba uznání'],
  mooninvirgo: ['kritický a analyzující', 'potřeba čistoty a pořádku'],
  mooninlibra: ['potřeba harmonie a vztahů', 'emocionální vyrovnanost'],
  mooninscorpio: ['intenzivní a hluboký', 'sklon k emocionálním tajemstvím'],
  mooninsagittarius: ['optimistický a nezávislý', 'emoce spojené s cestováním'],
  moonincapricorn: ['disciplinovaný a zodpovědný', 'emocionálně rezervovaný'],
  mooninaquarius: ['nezávislý a originální', 'emoce spojené s přátelstvím'],
  mooninpisces: ['snílek a citlivý', 'potřeba duchovního spojení'],

  // Mars in all zodiac signs
  marsinaries: ['akční a odvážný', 'rychlý a impulzivní'],
  marsintaurus: ['vytrvalý a stálý', 'pragmatický přístup k akci'],
  marsingemini: ['inteligentní a zvídavý', 'zájem o nové myšlenky'],
  marsincancer: ['citově motivovaný', 'ochrana rodiny'],
  marsinleo: ['sebevědomý a dramatický', 'touha po uznání'],
  marsinvirgo: ['metodický a přesný', 'zaměření na detaily'],
  marsinlibra: ['spolupráce a harmonický přístup', 'diplomacie'],
  marsinscorpio: ['vášnivý a intenzivní', 'silné emocionální reakce'],
  marsinsagittarius: ['dobrodružný a optimistický', 'akce směrem k ideálům'],
  marsincapricorn: ['pracovitý a disciplinovaný', 'plánovaná akce'],
  marsinaquarius: ['originální a nezávislý', 'akce pro změnu společnosti'],
  marsinpisces: ['snílek a intuitivní', 'akce vedená emocemi'],

  // Venus in all zodiac signs
  venusinaries: ['vášnivý a romantický', 'rychlé projevy náklonnosti'],
  venusintaurus: ['věrný a smyslný', 'potřeba stability v lásce'],
  venusingemini: ['zvídavý a hravý', 'potřeba intelektuálního spojení'],
  venusincancer: ['citově hluboký a starostlivý', 'potřeba bezpečí'],
  venusinleo: ['velkorysý a hrdý', 'potřeba obdivu v lásce'],
  venusinvirgo: ['pragmatický a skromný', 'péče vyjádřená praktickými činy'],
  venusinlibra: ['harmonický a diplomatický', 'potřeba rovnováhy ve vztazích'],
  venusinscorpio: ['intenzivní a vášnivý', 'hluboká emocionální pouta'],
  venussagittarius: ['dobrodružný a nezávislý', 'potřeba svobody v lásce'],
  venusincapricorn: ['seriózní a zodpovědný', 'důraz na stabilitu ve vztazích'],
  venusinaquarius: ['originální a nekonvenční', 'potřeba přátelství a volnosti'],
  venusinpisces: ['romantický a idealistický', 'hluboká empatie'],

  // Jupiter in all zodiac signs
  jupiterinaries: ['expanzivní a odvážný', 'tendence k rychlé akci'],
  jupiterintaurus: ['materiální prosperita', 'stabilní růst'],
  jupiteringemini: ['rozvoj vědění a komunikace', 'touha po vzdělání'],
  jupiterincancer: ['ochrana a expanze rodiny', 'emocionální prosperita'],
  jupiterinleo: ['velkorysý a dramatický', 'touha po uznání ve velkém měřítku'],
  jupiterinvirgo: ['růst skrze službu a organizaci', 'pragmatický přístup k rozvoji'],
  jupiterinlibra: ['harmonie a spravedlnost', 'růst ve vztazích'],
  jupiterinscorpio: ['intenzivní a vášnivý', 'expanze skrze transformaci'],
  jupiterinsagittarius: ['optimistický a idealistický', 'růst skrze cestování a filozofii'],
  jupiterincapricorn: ['disciplinovaný a ambiciózní', 'plánovaný růst'],
  jupiterinaquarius: ['nezávislý a originální', 'expanze skrze společenské změny'],
  jupiterinpisces: ['duchovní a empatický', 'růst skrze fantazii a umění'],

  // Saturn in all zodiac signs
  saturninaries: ['disciplinovaný a odvážný', 'akce s rozvahou'],
  saturnintaurus: ['stabilní a pracovitý', 'materiální disciplína'],
  saturningemini: ['rozvážný a zodpovědný', 'disciplína ve vědění'],
  saturnincancer: ['ochrana rodiny a emocí', 'emocionální disciplína'],
  saturninleo: ['sebevědomý a hrdý', 'potřeba respektu ve společnosti'],
  saturninvirgo: ['precizní a organizovaný', 'disciplína ve službě'],
  saturninlibra: ['spravedlivý a diplomatický', 'disciplína ve vztazích'],
  saturninscorpio: ['intenzivní a kontrolující', 'transformační disciplína'],
  saturninsagittarius: ['filozofický a rozvážný', 'disciplína ve vzdělání'],
  saturnincapricorn: ['ambiciózní a disciplinovaný', 'potřeba zodpovědnosti a kariérního růstu'],
  saturninaquarius: ['originální a nezávislý', 'disciplína pro společenské změny'],
  saturninpisces: ['snílek a idealista', 'disciplína v duchovním růstu'],

  merkurinaries: ['rychlý a bystrý', 'komunikativní a analytický'],
  merkurintaurus: ['praktický a realistický', 'pomalý, ale důvtipný'],
  merkuringemini: ['intelektuální a zvídavý', 'vynikající komunikátor'],
  merkurincancer: ['citlivý a empatický', 'komunikace o emocích'],
  merkurinleo: ['tvůrčí a dramatický', 'schopnost zaujmout'],
  merkurinvirgo: ['analytický a metodický', 'detailista v komunikaci'],
  merkurinlibra: ['harmonický a diplomatický', 'schopnost vyjednávat'],
  merkurinscorpio: ['intenzivní a tajemný', 'schopnost odhalit pravdu'],
  merkurinsagittarius: ['optimistický a filozofický', 'rozšíření obzorů myšlení'],
  merkurincapricorn: ['praktický a strukturovaný', 'efektivní komunikace'],
  merkurinaquarius: ['inovativní a originální', 'neortodoxní myšlení'],
  merkurinpiscis: ['intuitivní a imaginativní', 'komunikace s emocionálním nádechem'],

  // Pluto in all zodiac signs
  plutoinaries: ['transformační a mocný', 'změny ve společnosti'],
  plutointaurus: ['materiální transformace', 'změny v hodnotách'],
  plutoingemini: ['intelektuální transformace', 'změny v komunikaci'],
  plutoincancer: ['hluboká transformace', 'změny v rodině'],
  plutoinleo: ['silný a dominantní', 'změny v sebevědomí'],
  plutoinvirgo: ['metodický a transformativní', 'změny v práci'],
  plutoinlibra: ['transformace ve vztazích', 'změny v oblasti spravedlnosti'],
  plutoinscorpio: ['intenzivní a mocný', 'transformace skrze emoční hloubku'],
  plutoinsagittarius: ['filozofické a transformativní', 'změny v oblasti vzdělání'],
  plutoincapricorn: ['praktická transformace', 'změny ve společnosti a kariéře'],
  plutoinaquarius: ['revoluční a transformativní', 'změny pro budoucnost'],
  plutoinpisces: ['duchovní a transformativní', 'změny v emocionálním růstu'],
  
  // Neptune in all zodiac signs
  neptuneinaries: ['intuitivní a emocionální', 'fantazie ve společnosti'],
  neptuneintaurus: ['smyslový a emocionální', 'fantazie v oblasti majetku'],
  neptuneingemini: ['intuitivní myšlení', 'fantazie v komunikaci'],
  neptuneincancer: ['citlivý a emocionální', 'fantazie v rodině'],
  neptuneinleo: ['umělecký a dramatický', 'fantazie v umění'],
  neptuneinvirgo: ['pragmatická intuice', 'fantazie v práci a zdraví'],
  neptuneinlibra: ['harmonická intuice', 'fantazie v oblasti vztahů'],
  neptuneinscorpio: ['hluboká intuice', 'fantazie v transformaci'],
  neptuneinpisces: ['spirituální a snový', 'fantazie v duchovním růstu'],
  neptuneincapricorn: ['praktická intuice', 'fantazie ve společnosti'],


  // Ascendent in all zodiac signs
  ascendentinaries: ['dynamický a aktivní', 'přitažlivý a charismatický'],
  ascendentinauries: ['stabilní a spolehlivý', 'vytrvalý a praktický'],
  ascendentingemini: ['komunikativní a zvídavý', 'všestranný a inteligentní'],
  ascendentincancer: ['citlivý a empatický', 'ochranný a pečující'],
  ascendentinleo: ['sebevědomý a kreativní', 'dominantní a inspirativní'],
  ascendentinvirgo: ['analytický a metodický', 'pečlivý a praktický'],
  ascendentinlibra: ['harmonický a diplomatický', 'přitažlivý a charismatický'],
  ascendentinscorpio: ['intenzivní a tajemný', 'silný a magnetický'],
  ascendentinsagittarius: ['optimistický a dobrodružný', 'filozofický a otevřený'],
  ascendentubcapricorn: ['ambiciózní a zodpovědný', 'pracovitý a disciplinovaný'],
  ascendentinaquarius: ['inovativní a originální', 'neortodoxní a svobodný'],
  ascendentinpisces: ['intuitivní a snový', 'empatický a kreativní'],

  chironaries: ['raněný vůdce', 'naučení se sebevědomí'],
  chirontaurus: ['raněná hodnota', 'naučení se sebeúcty'],
  chirongemini: ['raněná komunikace', 'naučení se vyjadřovat'],
  chironcancer: ['raněné emoce', 'naučení se emocí a rodiny'],
  chironleo: ['raněné sebevědomí', 'naučení se kreativity'],
  chironvirgo: ['raněné zdraví', 'naučení se disciplíně'],
  chironlibra: ['raněné vztahy', 'naučení se rovnováze'],
  chironscorpio: ['raněná moc', 'naučení se transformaci'],
  chironsagittarius: ['raněná filozofie', 'naučení se otevřenosti'],
  chironcapricorn: ['raněná autorita', 'naučení se zodpovědnosti'],
  chironaquarius: ['raněná individualita', 'naučení se svobodě'],
  chironpisces: ['raněná duchovnost', 'naučení se soucitu'],

  // Uran in all zodiac signs
  uraninaries: ['inovativní a nezávislý', 'revoluce v osobnosti'],
  uranusintaurus: ['praktické inovace', 'změny v hodnotách a financích'],
  uranusgemini: ['rychlé myšlení a komunikace', 'revoluční myšlení'],
  uranusincancer: ['emocionální transformace', 'změny v rodinných vztazích'],
  uranusinleo: ['tvůrčí a expresivní', 'inovace v umění a seberealizaci'],
  uranusinviro: ['metodický, ale inovativní', 'změny v práci a zdraví'],
  uranuslibra: ['revoluční vztahy', 'změny v oblasti spravedlnosti'],
  uranusinscorpio: ['intenzivní inovace', 'změny skrze transformaci'],
  uranusinsagittarius: ['dobrodružné inovace', 'revoluce v oblasti vzdělání a filozofie'],
  uranusincapricorn: ['praktické, ale revoluční', 'změny ve společnosti a kariéře'],
  uranusinaquarius: ['neomezený a originální', 'inovace pro budoucnost'],
  uranusinpiscis: ['duchovní inovace', 'změny v emocionálním růstu a intuici'],
  
}