export const zodiacSigns = [
  {
    name: 'Aries',
    element: 'Fire',
    ruler: 'Mars',
    color: 'Red',
    luckyDay: 'Tuesday',
    luckyNumbers: [1, 8, 17],
    strengths: ['Courageous', 'Determined', 'Confident', 'Enthusiastic', 'Optimistic', 'Honest', 'Passionate'],
    weaknesses: ['Impatient', 'Moody', 'Short-tempered', 'Impulsive', 'Aggressive'],
    klady: ['odvážný', 'rozhodný', 'sebevědomý', 'nadšený', 'optimistický', 'upřímný', 'vášnivý'],
    slabiny: ['netrpělivý', 'náladový', 'nesnášenlivý', 'impulzivní', 'agresivní'],
    likes: ['Comfortable clothes', 'Taking on leadership roles', 'Physical challenges', 'Individual sports'],
    dislikes: ['Inactivity', 'Delays', 'Work that does not use one\'s talents'],
    compatibility: ['Leo', 'Sagittarius'],
    compatibilityScore: 5,
    summary: 'As the first sign in the zodiac, the presence of Aries always marks the beginning of something energetic and turbulent. They are continuously looking for dynamic, speed and competition, always being the first in everything - from work to social gatherings.',
    imageUrl: 'https://www.astrology-zodiac-signs.com/images/aries.jpg',
    imageAlt: 'Aries',
  }, 
  {
    name: 'Taurus',
    element: 'Earth',
    ruler: 'Venus',
    color: 'Green, Pink',
    luckyDay: 'Friday',
    luckyNumbers: [2, 6, 9, 12, 24],
    strengths: ['Reliable', 'Patient', 'Practical', 'Devoted', 'Responsible', 'Stable'],
    weaknesses: ['Stubborn', 'Possessive', 'Uncompromising'],
    klady: ['spolehlivý', 'trpělivý', 'praktický', 'oddaný', 'zodpovědný', 'stabilní'],
    slabiny: ['tvrdohlavý', 'vlastnický', 'neústupný'],
    likes: ['Gardening', 'Cooking', 'Music', 'Romance', 'High quality clothes', 'Working with hands'],
    dislikes: ['Sudden changes', 'Complications', 'Insecurity of any kind', 'Synthetic fabrics'],
    compatibility: ['Virgo', 'Capricorn'],
    compatibilityScore: 5,
    summary: 'Practical and well-grounded, Taurus is the sign that harvests the fruits of labor. They feel the need to always be surrounded by love and beauty, turned to the material world, hedonism, and physical pleasures.',
    imageUrl: 'https://www.astrology-zodiac-signs.com/images/taurus.jpg',
    imageAlt: 'Taurus',
  },
  {
    name: 'Gemini',
    element: 'Air',
    ruler: 'Mercury',
    color: 'Light-Green, Yellow',
    luckyDay: 'Wednesday',
    luckyNumbers: [5, 7, 14, 23],
    strengths: ['Gentle', 'Affectionate', 'Curious', 'Adaptable', 'Ability to learn quickly and exchange ideas'],
    weaknesses: ['Nervous', 'Inconsistent', 'Indecisive'],
    klady: ['jemný', 'laskavý', 'zvědavý', 'přizpůsobivý', 'schopnost rychle se učit a vyměňovat nápady'],
    slabiny: ['nervózní', 'nestálý', 'rozhodování'],
    likes: ['Music', 'Books', 'Magazines', 'Chats with nearly anyone', 'Short trips around the town'],
    dislikes: ['Being alone', 'Being confined', 'Repetition and routine'],
    compatibility: ['Libra', 'Aquarius'],
    compatibilityScore: 5,
    summary: 'Expressive and quick-witted, Gemini represents two different personalities in one and you will never be sure which one you will face. They are sociable, communicative and ready for fun, with a tendency to suddenly get serious, thoughtful and restless.',
    imageUrl: 'https://www.astrology-zodiac-signs.com/images/gemini.jpg',
    imageAlt: 'Gemini',
  },
  {
    name: 'Cancer',
    element: 'Water',
    ruler: 'Moon',
    color: 'White',
    luckyDay: 'Monday',
    luckyNumbers: [2, 3, 15, 20],
    strengths: ['Tenacious', 'Highly imaginative', 'Loyal', 'Emotional', 'Sympathetic', 'Persuasive'],
    weaknesses: ['Moody', 'Pessimistic', 'Suspicious', 'Manipulative', 'Insecure'],
    klady: ['vytrvalý', 'velmi vynalézavý', 'věrný', 'emoční', 'empatický', 'přesvědčivý'],
    slabiny: ['náladový', 'pesimistický', 'podezřívavý', 'manipulativní', 'nejistý'],
    likes: ['Art', 'Home-based hobbies', 'Relaxing near or in water', 'Helping loved ones', 'A good meal with friends'],
    dislikes: ['Strangers', 'Any criticism of Mom', 'Revealing of personal life'],
    compatibility: ['Scorpio', 'Pisces'],
    compatibilityScore: 5,
    summary: 'Deeply intuitive and sentimental, Cancer can be one of the most challenging zodiac signs to get to know. They are very emotional and sensitive, and care deeply about matters of the family and their home.',
    imageUrl: 'https://www.astrology-zodiac-signs.com/images/cancer.jpg',
    imageAlt: 'Cancer',
  },
  {
    name: 'Leo',
    element: 'Fire',
    ruler: 'Sun',
    color: 'Gold, Yellow, Orange',
    luckyDay: 'Sunday',
    luckyNumbers: [1, 3, 10, 19],
    strengths: ['Creative', 'Passionate', 'Generous', 'Warm-hearted', 'Cheerful', 'Humorous'],
    weaknesses: ['Arrogant', 'Stubborn', 'Self-centered', 'Lazy', 'Inflexible'],
    klady: ['kreativní', 'vášnivý', 'štědrý', 'srdečný', 'veselý', 'humorný'],
    slabiny: ['arogantní', 'tvrdohlavý', 'egocentrický', 'líný', 'nepružný'],
    likes: ['Theater', 'Taking holidays', 'Being admired', 'Expensive things', 'Bright colors', 'Fun with friends'],
    dislikes: ['Being ignored', 'Facing difficult reality', 'Not being treated like a king or queen'],
    compatibility: ['Aries', 'Sagittarius'],
    compatibilityScore: 5,
    summary: 'People born under the sign of Leo are natural born leaders. They are dramatic, creative, self-confident, dominant and extremely difficult to resist, able to achieve anything they want to in any area of life they commit to.',
    imageUrl: 'https://www.astrology-zodiac-signs.com/images/leo.jpg',
    imageAlt: 'Leo',
  },
  {
    name: 'Virgo',
    element: 'Earth',
    ruler: 'Mercury',
    color: 'Grey, Beige, Pale-Yellow',
    luckyDay: 'Wednesday',
    luckyNumbers: [5, 14, 15, 23, 32],
    strengths: ['Loyal', 'Analytical', 'Kind', 'Hardworking', 'Practical'],
    weaknesses: ['Shyness', 'Worry', 'Overly critical of self and others', 'All work and no play'],
    klady: ['loajální', 'analytický', 'laskavý', 'pracovitý', 'praktický'],
    slabiny: ['ostýchavý', 'starost', 'příliš kritický k sobě a ostatním', 'všechna práce a žádná hra'],
    likes: ['Animals', 'Healthy food', 'Books', 'Nature', 'Cleanliness'],
    dislikes: ['Rudeness', 'Asking for help', 'Taking center stage'],
    compatibility: ['Taurus', 'Capricorn'],
    compatibilityScore: 5,
    summary: 'Virgos are always paying attention to the smallest details and their deep sense of humanity makes them one of the most careful signs of the zodiac. Their methodical approach to life ensures that nothing is left to chance.',
    imageUrl: 'https://www.astrology-zodiac-signs.com/images/virgo.jpg',
    imageAlt: 'Virgo',
  },
  {
    name: 'Libra',
    element: 'Air',
    ruler: 'Venus',
    color: 'Pink, Green',
    luckyDay: 'Friday',
    luckyNumbers: [4, 6, 13, 15, 24],
    strengths: ['Cooperative', 'Diplomatic', 'Gracious', 'Fair-minded', 'Social'],
    weaknesses: ['Indecisive', 'Avoids confrontations', 'Will carry a grudge', 'Self-pity'],
    klady: ['spolupracující', 'diplomatický', 'laskavý', 'spravedlivý', 'společenský'],
    slabiny: ['rozhodování', 'vyhýbání se konfrontacím', 'ponese vztek', 'sebelítost'],
    likes: ['Harmony', 'Gentleness', 'Sharing with others', 'The outdoors'],
    dislikes: ['Violence', 'Injustice', 'Brutishness', 'Being a homebody'],
    compatibility: ['Gemini', 'Aquarius'],
    compatibilityScore: 5,
    summary: 'People born under the sign of Libra are peaceful, fair, and they hate being alone. Partnership is very important for them, as their mirror and someone giving them the ability to be the mirror themselves.',
    imageUrl: 'https://www.astrology-zodiac-signs.com/images/libra.jpg',
    imageAlt: 'Libra',
  },
  {
    name: 'Scorpio',
    element: 'Water',
    ruler: 'Pluto, Mars',
    color: 'Scarlet, Red, Rust',
    luckyDay: 'Tuesday',
    luckyNumbers: [8, 11, 18, 22],
    strengths: ['Resourceful', 'Brave', 'Passionate', 'Stubborn', 'A true friend'],
    weaknesses: ['Distrusting', 'Jealous', 'Secretive', 'Violent'],
    klady: ['vynalézavý', 'statečný', 'vášnivý', 'tvrdohlavý', 'opravdový přítel'],
    slabiny: ['nedůvěřivý', 'žárlivý', 'tajnůstkářský', 'násilný'],
    likes: ['Truth', 'Facts', 'Being right', 'Long-time friends', 'Teasing', 'A grand passion'],
    dislikes: ['Dishonesty', 'Revealing secrets', 'Passive people'],
    compatibility: ['Cancer', 'Pisces'],
    compatibilityScore: 5,
    summary: 'Scorpio-born are passionate and assertive people. They are determined and decisive, and will research until they find out the truth. Scorpio is a great leader, always aware of the situation and also features prominently in resourcefulness.',
    imageUrl: 'https://www.astrology-zodiac-signs.com/images/scorpio.jpg',
    imageAlt: 'Scorpio',
  },
  {
    name: 'Sagittarius',
    element: 'Fire',
    ruler: 'Jupiter',
    color: 'Blue',
    luckyDay: 'Thursday',
    luckyNumbers: [3, 7, 9, 12, 21],
    strengths: ['Generous', 'Idealistic', 'Great sense of humor'],
    weaknesses: ['Promises more than can deliver', 'Very impatient', 'Will say anything no matter how undiplomatic'],
    klady: ['stědrý', 'idealista', 'velký smysl pro humor'],
    slabiny: ['slibuje víc než může dodat', 'velmi netrpělivý', 'řekne cokoli, bez ohledu na to, jak nediplomatické'],
    likes: ['Freedom', 'Travel', 'Philosophy', 'Being outdoors'],
    dislikes: ['Clingy people', 'Being constrained', 'Off-the-wall theories', 'Details'],
    compatibility: ['Aries', 'Leo'],
    compatibilityScore: 5,
    summary: 'Curious and energetic, Sagittarius is one of the biggest travelers among all zodiac signs. Their open mind and philosophical view motivates them to wander around the world in search of the meaning of life.',
    imageUrl: 'https://www.astrology-zodiac-signs.com/images/sagittarius.jpg',
    imageAlt: 'Sagittarius',
  },
  {
    name: 'Capricorn',
    element: 'Earth',
    ruler: 'Saturn',
    color: 'Brown, Black',
    luckyDay: 'Saturday',
    luckyNumbers: [4, 8, 13, 22],
    strengths: ['Responsible', 'Disciplined', 'Self-control', 'Good managers'],
    weaknesses: ['Know-it-all', 'Unforgiving', 'Condescending', 'Expecting the worst'],
    klady: ['zodpovědný', 'disciplinovaný', 'sebekontrola', 'dobří manažeři'],
    slabiny: ['všechno vědět', 'nesmlouvavý', 'pohrdavý', 'očekávání nejhoršího'],
    likes: ['Family', 'Tradition', 'Music', 'Understated status', 'Quality craftsmanship'],
    dislikes: ['Almost everything at some point'],
    compatibility: ['Taurus', 'Virgo'],
    compatibilityScore: 5,
    summary: 'Capricorn is a sign that represents time and responsibility, and its representatives are traditional and often very serious by nature. These individuals possess an inner state of independence that enables significant progress both in their personal and professional lives.',
    imageUrl: 'https://www.astrology-zodiac-signs.com/images/capricorn.jpg',
    imageAlt: 'Capricorn',
  },
  {
    name: 'Aquarius',
    element: 'Air',
    ruler: 'Uranus, Saturn',
    color: 'Light-Blue, Silver',
    luckyDay: 'Saturday',
    luckyNumbers: [4, 7, 11, 22, 29],
    strengths: ['Progressive', 'Original', 'Independent', 'Humanitarian'],
    weaknesses: ['Runs from emotional expression', 'Temperamental', 'Uncompromising', 'Aloof'],
    klady: ['progresivní', 'originál', 'nezávislý', 'humanitární'],
    slabiny: ['utíká od emocionálního vyjádření', 'vztek', 'neústupný', 'odtažitý'],
    likes: ['Fun with friends', 'Helping others', 'Fighting for causes', 'Intellectual conversation', 'A good listener'],
    dislikes: ['Limitations', 'Broken promises', 'Being lonely', 'Dull or boring situations', 'People who disagree with them'],
    compatibility: ['Gemini', 'Libra'],
    compatibilityScore: 5,
    summary: 'Aquarius-born are shy and quiet , but on the other hand they can be eccentric and energetic. However, in both cases, they are deep thinkers and highly intellectual people who love helping others. They are able to see without prejudice, on both sides, which makes them people who can easily solve problems.',
    imageUrl: 'https://www.astrology-zodiac-signs.com/images/aquarius.jpg',
    imageAlt: 'Aquarius',
  },
  {
    name: 'Pisces',
    element: 'Water',
    ruler: 'Neptune, Jupiter',
    color: 'Mauve, Lilac, Purple, Violet, Sea green',
    luckyDay: 'Thursday',
    luckyNumbers: [3, 9, 12, 15, 18, 24],
    strengths: ['Compassionate', 'Artistic', 'Intuitive', 'Gentle', 'Wise', 'Musical'],
    weaknesses: ['Fearful', 'Overly trusting', 'Sad', 'Desire to escape reality', 'Can be a victim or a martyr'],
    klady: ['milosrdný', 'umělecký', 'intuitivní', 'jemný', 'moudrý', 'hudební'],
    slabiny: ['bojácný', 'příliš důvěřivý', 'smutný', 'touha uniknout z reality', 'může být obětí nebo mučedníkem'],
    likes: ['Being alone', 'Sleeping', 'Music', 'Romance', 'Visual media', 'Swimming', 'Spiritual themes'],
    dislikes: ['Know-it-all', 'Being criticized', 'The past coming back to haunt', 'Cruelty of any kind'],
    compatibility: ['Cancer', 'Scorpio'],
    compatibilityScore: 5,
    summary: 'Pisces are very friendly, so they often find themselves in a company of very different people. Pisces are selfless, they are always willing to help others, without hoping to get anything back.',
    imageUrl: 'https://www.astrology-zodiac-signs.com/images/pisces.jpg',
    imageAlt: 'Pisces',
  },
]
